### ISSUE TITLE
Use relative paths in error results

### ISSUE THREAD

**Issue by laurentgoudet** [spalger/gulp-jshint#101]
The JSHint "spec" (http://jshint.com/docs/reporters/) describe the "file" key as a relative path (file: 'demo.js') and grunt-jshint also uses that format. Changing file.path to file.relative in lint.js/reportErrors would allow the reporters to output paths relative to the project's root, removing some clutter from the jshint output.

However a test (integration/fileIgnored.js) is making sure that the base property is not accessed, which is the case with the file.relative assessor. Is there any reason to use an absolute path? Would an extra option could be added for that?

**Comment by spalger** [comment]
gulp-jshint should be behaving as similar to jshint as possible. Do you feel up to submitting a pull-request?

It would be awesome if it came with tests that prove the gulp-jshint output matches the jshint output as closely as possible, but it's not required!

**Comment by IcanDivideBy0** [comment]
+1
