### ISSUE TITLE
Use jshint 2.6

### ISSUE THREAD

**Issue by openback** [spalger/gulp-jshint#102]
2.6 updates has a quite a few bugfixes, a couple of which I'm hitting right now. Can we get that updated? Thanks!

**Comment by jgoldsmith-ecs** [comment]
@openback Per `package.json`, this library uses jshint `^2.5.6`, so it already allows 2.6.x.  However, I would recommend locking jshint to 2.6.0 because of a breaking change with ignore blocks not being parsed correctly.  See https://github.com/jshint/jshint/issues/2215 for details.

**Comment by swashcap** [comment]
:+1:

**Comment by iclanzan** [comment]
I really need the updated jshint too.

**Comment by gasolin** [comment]
It's now jshint 2.7. some es6 features such as template string lint is required for newer version

**Comment by b-long** [comment]
:+1:
