### ISSUE TITLE
Question: Gulp task cannot be killed with Ctrl-C?

### ISSUE THREAD

**Issue by adjavaherian** [spalger/gulp-jshint#112]
I'm wondering why I'm unable to SIGINT my hint task when I'm using gulp-jshint?

```javascript
var gulp        = require('gulp');
var jshint      = require('gulp-jshint');
var config      = require('../config').jsHint;
var stylish     = require('jshint-stylish');
var plumber     = require('gulp-plumber');
var react       = require('gulp-react');
var jscs 		= require('gulp-jscs');

gulp.task('hint', function() {

    return gulp.src([config.appjsx, config.config, config.server])
        .pipe(plumber())
        .pipe(react())
        .pipe(jscs())
        .pipe(jshint())
        .pipe(jshint.reporter(stylish))
        .pipe(jshint.reporter('fail'));

});

```

w/ gulp-jshint@1.11.0 

It just lints and hangs after the last notification, then it becomes un-killable.  Should at least return, no?

SIGKILL (ctrl-\) works, but it dumps core.

**Comment by contra** [comment]
it's probably jshint itself locking the process, i would open a ticket there

**Comment by adjavaherian** [comment]
Err, my bad.  Not a good idea to recursively hint into a big ugly webpack bundle.  Works well when I remove the bundle from the source.  Thanks.
