### ISSUE TITLE
Error in plugin 'gulp-jshint'

### ISSUE THREAD

**Issue by bimalvv** [spalger/gulp-jshint#115]
Hi,

When I tried to use

```javascript
return gulp
		.src(['./src/**/*.js'])
		.pipe(jscs())
		.pipe(jshint())
		.pipe(jshint.reporter('jshint-stylish', {
			verbose: true
		}));
```
I am getting error as shown below

```
[10:08:03] Error in plugin 'gulp-jshint'
Message:
    Invalid reporter
```

But if I replace 'jshint-stylish' with 'default' it is working fine and I am using "gulp-jshint": "^1.11.0"

Is there any change in 'jshint-stylish' or am I missing something?

Thanks,
Bimal

**Comment by spalger** [comment]
Do you have the jshint-stylish node module installed?

**Comment by bimalvv** [comment]
It was missing.

Thanks,
Bimal
