### ISSUE TITLE
ES6 export function lint problem

### ISSUE THREAD

**Issue by joseph-norman** [spalger/gulp-jshint#119]
Hi all

When using the exported generator functionality in ES6:

```
export function test() {
..
}
```

I'm getting a lint issue, `'test' was used before it was defined`. Looking around, this looks like it was fixed in jshint version 2.9.0. Does this sound familiar? Would it be possible to upgrade the jshint version to 2.9.x?

**Comment by spalger** [comment]
Reinstalling gulp-jshint will update jshint to the latest version published in the 2.x branch. 2.9 has not been published to [npm](https://www.npmjs.com/package/jshint) yet, which is why it's not installing.
