### ISSUE TITLE
Need an option for report absolute paths

### ISSUE THREAD

**Issue by Delagen** [spalger/gulp-jshint#126]

**Comment by spalger** [comment]
Does jshint offer this option?

**Comment by Delagen** [comment]
In your code 69c9c17e
```
 var filePath = file.path ? path.relative(process.cwd(), file.path): 'stdin';
```

**Comment by Delagen** [comment]
???

**Comment by spalger** [comment]
@delagen I'm asking if the proper jshint tool offers this

**Comment by Delagen** [comment]
Your plugin generate only data for reporter. Reporter only output what you supplied.

So if your reportErrors in [lint.js](https://github.com/spalger/gulp-jshint/blob/master/src/lint.js#L43) will make absolute path, reporter output that.

So I and remove this plugin from my code. Needed to me plugin functionality fits in about 60 lines.
