### ISSUE TITLE
Problem with .jshintignore

### ISSUE THREAD

**Issue by 6aKa** [spalger/gulp-jshint#13]
JSHINT not useing .jshintignore for excludeing directories.

And be very good if

<pre>
if (!opt) opt = '.jshintrc';
</pre>

**Comment by joshstrange** [comment]
Just for the record for anyone else that comes across this it is working for me with the following setup:

    /
      gulpfile.js
      .jshintignore
      webroot/
        source/
          js/
            modified.third.party.lib.js

and ````.jshintignore```` having the following in it:

    webroot/source/js/modified.third.party.lib.js

and my gulp task being:

    gulp.task('lint', function () {
      gulp.src(jsSourceGlob)
        .pipe(jshint('.jshintrc'))
        .pipe(jshint.reporter('jshint-stylish'));
    });

**Comment by EdwardBeckett** [comment]
@joshstrange That's the ticket +1
