### ISSUE TITLE
Please add CHANGELOG.md

### ISSUE THREAD

**Issue by simison** [spalger/gulp-jshint#132]
Would be great, now I have no idea what has changed between v1 and v2 (supposed to be breaking change by semver).

Thanks!

**Comment by spalger** [comment]
As you can see from the very simple commit log, jshint is now required as a peerDependency. This is a breaking change for anyone using npm 3 (mostly via node 5).

![image](https://cloud.githubusercontent.com/assets/1329312/11456196/cabf29ce-9646-11e5-8ae8-9f2ed8dd222d.png)

I really don't think this is complex enough to warrant a changelog
