### ISSUE TITLE
The peer dependency jshint@2.x included from gulp-jshint will no longer be automatically installed to fulfill the peerDependency in npm 3+. Your application will need to depend on it explicitly.

### ISSUE THREAD

**Issue by roninliu** [spalger/gulp-jshint#135]
The peer dependency jshint@2.x included from gulp-jshint will no longer be automatically installed to fulfill the peerDependency in npm 3+. Your application will need to depend on it explicitly.

**Comment by spalger** [comment]
Please [note the readme](https://github.com/spalger/gulp-jshint#install), you must install jshint along with gulp-jshint
