### ISSUE TITLE
Upgrade minimatch

### ISSUE THREAD

**Issue by ryuran** [spalger/gulp-jshint#144]
```npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue```

**Comment by sauls** [comment]
Having same error :disappointed:

**Comment by Anurag0502** [comment]
Just type in "npm install -g minimatch@3.0.2" (Without the quotes). That will do
![minimatch_error_update_3_0_2](https://cloud.githubusercontent.com/assets/20483284/16890244/6a65a5fc-4b0a-11e6-88f6-a8b4dfcaa3a1.png)

**Comment by ryuran** [comment]
It can be a work-around but not the solution.

**Comment by Aashima89** [comment]
Any updates on whether minimatch version will be upgraded?

**Comment by rafaelcamargo** [comment]
+1

**Comment by Schnitzel** [comment]
+1 all our builds on around 100 sites are showing the warning :)

**Comment by thecantero** [comment]
👍 on on fixing this

**Comment by richardschneider** [comment]
Is there a NPM release coming soon?

**Comment by spalger** [comment]
@richardschneider it's on my list for today

**Comment by spalger** [comment]
Just published 2.0.2
