### ISSUE TITLE
Can't jshint be moved to dependencies?

### ISSUE THREAD

**Issue by Reinmar** [spalger/gulp-jshint#145]
As of NPM3 `peerDependencies` are not supported (https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/). This means that if I install `gulp-jshint` without installing `jshint` in my package, `gulp-jscs` is not going to work.

I've seen https://github.com/spalger/gulp-jshint/issues/135 but it doesn't clarify why jshint hasn't been moved to normal dependencies. Is this because of backward compatibility with NPM2? And why does JSHint need to be installed as a peer dep?

**Comment by spalger** [comment]
It could be moved to the dependencies, but jshint should be installed in projects that are using it so that those projects can pick a specific version of jshint and still use the latest version of gulp-jshint.
