### ISSUE TITLE
gulp-jhint bad ender error

### ISSUE THREAD

**Issue by sreekanthjnayar** [spalger/gulp-jshint#158]
While running the gulp-jshint the following error is generated for every file in the code base
process line 0, col 0, Bad option: 'ender' 
There are certain forums which talk about the file format being the culprit to this issue. Is there a way to suppress this, coz this saturates the output generated by gulp.

OS - macOS High Sierra v10.13.3
IDE - vscode
gulp version - 4.0.0
gulp jshint version - 2.1.0
jshint version - 2.9.5

**Comment by TheDancingCode** [comment]
Check if you have an option called `"ender"` in your jshint config. If so, remove it.

**Comment by sreekanthjnayar** [comment]
Removing the ender option worked. Thanks for the prompt reply.
