### ISSUE TITLE
How to specify a jshint configuration file?

### ISSUE THREAD

**Issue by goloroden** [spalger/gulp-jshint#17]
How do I specify the path and name of the configuration file I'd like to use for JSHint, if it's not the default path and file name?

**Comment by ddietzel** [comment]
Put this in the docs, took me an hour to find this

**Comment by spalger** [comment]
@ddietzel this is mentiond in the paragraph underneath the code samples here: https://github.com/spalger/gulp-jshint/blob/master/README.md#options

Happy to consider a pull request improving this

**Comment by Spongman** [comment]
you give what looks like a complete list of the available options: "loopup, linter" and then add some additional verbose text below explaining that, no, those aren't all the options, if you want the complete list you have to read this bit too.

if you're going to give a list, at least make it complete.

and, no. no PR from me.
