### ISSUE TITLE
jshint.reporter('fail') when used in an async task doesn't fail the build

### ISSUE THREAD

**Issue by ScottWeinstein** [spalger/gulp-jshint#28]
Given the following

``` js
gulp.task('lint', function () {
    return gulp.src(['t*.js'])
    .pipe(jshint())
    .pipe(jshint.reporter('default'))
    .pipe(jshint.reporter('fail'));
})
gulp.task('default', ['lint'], function () {});
```

when run the default task isn't reached, which is good and expected, but the process exit code is 0, so the build isn't considered failed.

**Comment by ajbogh** [comment]
Possibly related, I found that if you used on('error') to exit the process after a jshint failure the jshint.reporter('fail') won't fire. To fix this I exit the process on('end') using a variable that I set on('error')

    var error = false;
    return gulp.src(constants.APP_JS_FILES)
        .pipe(jshint())
        .pipe(jshint.reporter('default'))
        .pipe(jshint.reporter('fail'))
        .on('error', function(e){
            error = true;
        })
        .on('end', function(){
            if(error) {
                process.exit();
            }
        });
