### ISSUE TITLE
Gulp watch with myReporter example hangs task 

### ISSUE THREAD

**Issue by joemaller** [spalger/gulp-jshint#50]
I was playing around with gulp watch and custom reporters when ran into an issue.

Everything works on the first pass, but the second time the `jshint` task is called, the stream gets stuck and the task no longer works. 

To be fair, this isn't really a gulp-jshint issue. What seems to be happening is that `myReporter` is being reused and somehow that causes the stream to hang. If the function is piped inline everything works because the inline function will be freshly instantiated on each run.

I reduced it down to this: 

```
var myReporter = map(function (file, cb) {
  console.log(file.relative);
  cb(null, file);
});
```

Usually the second task run will just hang silently, but for whatever reason piping `gulp-debug()` before `myReporter` causes it to throw this error:

```
/home/joe/node_modules/map-stream/index.js:90
    if(ended) throw new Error('map stream is not writable')
```

One quick solution is to wrap the `map` call in a function so a new instance is used each time:

```
var myReporter = function(file, cb) {
  return map(function(file, cb) {
    console.log(file.relative);
    cb(null, file);
  });
};
```

then in the task, call the function from the pipe:

```
.pipe(myReporter())
```

**Comment by leocaseiro** [comment]
Perfect @joemaller, worked like a charm
