### ISSUE TITLE
Support jsxhint

### ISSUE THREAD

**Issue by MoOx** [spalger/gulp-jshint#55]
I was about to fork this a update jshint call to jsxhint but at the same time I told myself I'll have to maintain this & check gulp-jshint update all the time to reintegrate.
What do you think about a PR to just add support for jsxhint ? (which is just a transform piped to jshint)

**Comment by elierotenberg** [comment]
There are problems with this method: the output of the JSX transform can break your rules although you original code didn't. For example, JSX can not be configured to output single-quoted code. The output with the `--harmony` flag can also produce ugly code, notably when using generators or destructuring assignment.

If someone has an efficient flow to make gulp, jshint, ES6 and jsx all play nice together I'd be very interested.

**Comment by arendjr** [comment]
+1 for native JSX support, so that I don't need those ugly /* jshint ... */ exceptions in my render() methods anymore :)
