### ISSUE TITLE
Fail reporter : events.js:72 error

### ISSUE THREAD

**Issue by hajarasoahaingo** [spalger/gulp-jshint#82]
Given this task:

    stuff
      .pipe(jshint())
      .pipe(jshint.reporter('jshint-stylish'))
      .pipe(jshint.reporter('fail'))

I got this when my lint throws an error after the stylish reporting:

<pre>
$ gulp lint
[21:33:06] Using gulpfile /path/to/gulpfile.js
[21:33:06] Starting 'lint'...
[21:33:07] Finished 'lint' after 465 ms

/file.js
  line 4  col 1  Use the function form of "use strict".

  ⚠  1 warning

events.js:72
        throw er; // Unhandled 'error' event

Error: JSHint failed for: /file.js
</pre>

My packages.json:

<pre>
"devDependencies": {
    "gulp": "latest",
    "gulp-jshint": "^1.8.5",
    "jshint-stylish": "^1.0.0",
  }
</pre>

**Comment by keradus** [comment]
Have same error on 1.10 version :(
Any news on that?

**Comment by afontaine** [comment]
Same issue, OS is Windows 7.

packages.json:

```json
"devDependencies": {
    "gulp": "^3.9.0",
    "gulp-connect": "^2.2.0",
    "gulp-jscs": "^3.0.0",
    "gulp-jshint": "^1.11.2",
    "jscs-stylish": "^0.3.1",
    "jshint-stylish": "^2.0.1"
  }
```

gulp task:

```javascript
gulp.task('js:hint', function () {
  return gulp.src('app/**/*.js')
    .pipe(jshint())
    .pipe(jshint.reporter('jshint-stylish'))
    .pipe(jshint.reporter('fail'));
});
```

**Comment by spalger** [comment]
This is what the fail report is supposed to do, when an error is detected it emits an error which will cause node to terminate unless it is handled. Not sure why this ticket was left open.

**Comment by afontaine** [comment]
Yes, for some reason I thought it was crashing `gulp.watch()`. It must have been something else.
