### ISSUE TITLE
Able to specify jshint function

### ISSUE THREAD

**Issue by jtangelder** [spalger/gulp-jshint#89]
I want to use [this jsxhint](https://github.com/shmatov/jshint-jsx) plugin, in combination with this gulp-jshint task. An option to provide/overrule the linter would be awesome.

````js
.pipe(jshint({ jshint: require('jshint-jsx').JSXHINT }))
````

**Comment by spenceralger** [comment]
@jtangelder I like this as it also supports using gulp-jshint with a different version of jshint than what is bundled. Can you try out the PR to see if it works for you?

With recent versions of npm you can install it by running  this in your project:
```sh
npm install spenceralger/gulp-jshint#overrideJshint
```

**Comment by Pomax** [comment]
Using this, I end up getting "C:\Users\Mike\Documents\Git projects\collaborations\mofo-example-app\react code\editor-app.jsx: line 0, col 0, Bad option: 'jshint'." errors for my .jsx files. Seems like the linter override option is being passed on to jshint/whatever linter was bound?
