### ISSUE TITLE
jsxhint support?

### ISSUE THREAD

**Issue by Pomax** [spalger/gulp-jshint#90]
Given https://www.npmjs.com/package/jsxhint and its ability to do linting for JS with React's JSX syntax, it would be incredibly useful if there was a way to tell gulp-jshint that the actual processor should be the jsxhint wrapper, which is a transparent wrapper around jshint and has exactly the same behaviour and API.

**Comment by spenceralger** [comment]
@Pomax can you try out the overrideJshint branch to see if it works for you? Checkout #89 for more info

**Comment by Pomax** [comment]
hm, the docs on how to use this added functionality is not really clear to me. I'm looking at https://github.com/spenceralger/gulp-jshint/blob/e66e29649a7013469ff0cb1de0ceaf4025546445/README.md but "Default is require('jshint').JSHINT" does not tell me what is happening here. Is that a number or string constant? is it a function? Is it actually an entire module?

Concretely, if I have the following bits:
```
var gulp = require("gulp");
var jshint = require("gulp-jshint");
var jsx = require("jsxhint");
gulp.task("lint", function() {
  // ...
});
```
Do  I use the following?
```
var jsxhinter = jslint({ jslint: jsx });
gulp.src(...)
  .pipe(jsxhinter)
  .pipe(...)
```

**Comment by spenceralger** [comment]
Thanks for taking the time to check it out @Pomax! I fixed a bug and updated [the docs](https://github.com/spenceralger/gulp-jshint/blob/overrideJshint/README.md#options), *hopefully* it is  more clear now. I also simplified the option a bit, so that you can pass just a module name (ie `{ jshint: 'jsxhint' }`) and gulp-jshint will just try to require that module. Or you can pass a function that is supposed to be a "drop in replacement" for jshint (ie. `{ jshint: require('jsxhint').JSHINT }`)

**Comment by Pomax** [comment]
nice! It might be worthwhile to extend that so that `linter` can be given either a string or an object - if it's a string then use it for `require(...)` calls, if it's an object, treat it as "this is already the a linter library, and needs to have a function called `...` which I will call."

That way, gulp-jshint can be given custom, not-a-node_module libraries, provided they use the same functions that jshint, jsxhint, etc. already use. That also allows people to either say `linter: "jsxhint"` or, explicitly, `var jsx = require("jsxhint"); ... /* code involving jsx */ ... ; var opts = {linter: jsx}; ...`

**Comment by Pomax** [comment]
I tried the updated version, but it looks like it might not be binding correctly because it's assuming the `JSHINT` variable exists. Using a workaround I can get that to work:

```
  var jsxhinter = require('jshint-jsx');
  jsxhinter.JSHINT = jsxhinter.JSXHINT;
  var jsxhint = jshint({ linter: 'jshint-jsx' });
  gulp.src(...).pipe(jsxhint).pipe(...);
```
Given that property of linters, it might be worth having two arguments:

```
{
  ...
  linter: 'jsxhint', // or require('jsxhint')
  main: 'JSXHINT'
}
```
That way the code will know both what to work with, and what the main entry point into the linter is, so that failures due to assumed function names is a thing of the past =)

**Comment by joemaller** [comment]
The code from the `overrideJshint` branch's README didn't work for me, but @Pomax 's snippet did. I couldn't get it to work with `jsxhint`, but it looks like [jsxhint might be done anyway](https://github.com/STRML/JSXHint/issues/45#issuecomment-71152608). Should probably change the reference in the readme.

**Comment by yoni-tock** [comment]
@joemaller what do you mean by "jsxhint might be done anyway"? Is there any update on this? The branch is now behind master by a decent chunk. I'd be happy to jump in and help!

**Comment by joemaller** [comment]
@yoni-tock The jsxhint project owner (@STRML) said "I will be sunsetting this project soon." [link](https://github.com/STRML/JSXHint/issues/45#issuecomment-71152608)

**Comment by yoni-tock** [comment]
@joemaller ah, got it.

**Comment by Pomax** [comment]
if you scroll down from where you linked, @joemaller, that issues seems to then concludes with what looks like "actually, this is totally fixable stand down alert, fixed in [issue number]"
